# Task - 1: Creating NumPy Arrays

In [1]:
import numpy as np

In [4]:
# 1D Array of integers from 1 to 10
A_1D = np.arange(1,11)
A_1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# 2D Array of shape(3,3) with values from 1 to 9
A_2D = np.reshape(np.arange(1,10),(3,3))
A_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# array from the list [10,20,30,40,50]
l = [10,20,30,40,50]
a = np.array(l)
a

array([10, 20, 30, 40, 50])

In [10]:
# shape of arrays
print(A_1D.shape)
print(A_2D.shape)
print(a.shape)

(10,)
(3, 3)
(5,)


In [11]:
# data type of each array

print(type(A_1D))
print(type(A_2D))
print(type(a))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


# Task 2: Important Mathematical Opertions

In [14]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
print(A)
B

[10 20 30 40]


array([1, 2, 3, 4])

In [15]:
# Addition
print (A+B)

array([11, 22, 33, 44])

In [17]:
# Substraction
A-B

array([ 9, 18, 27, 36])

In [18]:
# Multiplication
A*B

array([ 10,  40,  90, 160])

In [19]:
# Division

A/B

array([10., 10., 10., 10.])

In [20]:
# power

A**2

array([ 100,  400,  900, 1600])

In [21]:
# by using functions

np.add(A,B)

array([11, 22, 33, 44])

In [23]:
np.subtract(A,B)

array([ 9, 18, 27, 36])

# 3: Important NumPy Mathematical Formulas

In [24]:
values = np.array([2,4,6,8,10])

In [27]:
np.sqrt(values)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [28]:
np.exp(values)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

In [29]:
np.log(values)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

In [30]:
np.sum(values)

np.int64(30)

In [31]:
np.cumsum(values)

array([ 2,  6, 12, 20, 30])

# Task 4: Aggregation Operations

In [33]:
data = np.array([[10,20,30],
                [40,50,60],
                [70,80,90]])
data

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [35]:
# Maximum value
np.max(data)

np.int64(90)

In [37]:
# Minimum value
np.min(data)

np.int64(10)

In [38]:
# Overall mean
np.mean(data)

np.float64(50.0)

In [39]:
# row sise sum

np.sum(data,axis=1)

array([ 60, 150, 240])

In [40]:
# Column-wise sum
np.sum(data,axis=0)

array([120, 150, 180])

# Task 5: Statistical Operations

In [41]:
marks = np.array([78,85,90,66,72,88,95,60])
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [42]:
# mean
np.mean(marks)

np.float64(79.25)

In [43]:
# median
np.median(marks)

np.float64(81.5)

In [46]:
# variance
np.var(marks)

np.float64(134.1875)

In [48]:
# standard deviation
np.std(marks)

np.float64(11.583932838203095)

In [45]:
# minimum and maximum
print("minimum marks : ",np.min(marks))
print("maximum marks : ",np.max(marks))

minimum marks :  60
maximum marks :  95


In [50]:
# Range (max - min)
np.ptp(marks)

np.int64(35)

# Task 6: Percentiles and Sorting

In [51]:
marks

array([78, 85, 90, 66, 72, 88, 95, 60])

In [52]:
# sort the array
np.sort(marks)

array([60, 66, 72, 78, 85, 88, 90, 95])

In [53]:
# 25th percentile
np.percentile(marks,25)

np.float64(70.5)

In [54]:
# 50th percentile
np.percentile(marks,50)

np.float64(81.5)

In [55]:
# 75th percentile
np.percentile(marks,75)

np.float64(88.5)

In [58]:
# student count whos score above the avarage marks

avg = np.mean(marks)
print("avg marks : ",avg)
sc = np.sum(marks > avg)
print ("student above average : ",sc)

avg marks :  79.25
student above average :  4


# Task 7: Sales Analysis

In [59]:
sales = np.array([1200, 1500, 900, 2000, 1800, 1700, 1600])
sales

array([1200, 1500,  900, 2000, 1800, 1700, 1600])

In [62]:
# 1 Total weekly sales 

print("Total weekly sales : ",np.sum(sales))

Total weekly sales :  10700


In [64]:
# 2 Average daily sales
print("Avg daily sales : ",np.mean(sales))

Avg daily sales :  1528.5714285714287


In [65]:
# Highest and Lowest sales day

print ("Highest Sale day : ",np.max(sales))
print("Lowest sales day : ",np.min(sales))

Highest Sale day :  2000
Lowest sales day :  900


In [66]:
# 4 standerd deviation of sales
print("standard deviation of sales : ",np.std(sales))

standard deviation of sales :  345.2298849598449


In [71]:
# 5 sales above average

avg = np.mean(sales)
print("days where sales above average : ")
print("total number of days : ",np.sum(sales > avg))
print ("sales : ", np.where(sales > avg) )

days where sales above average : 
total number of days :  4
sales :  (array([3, 4, 5, 6]),)
