# Numpy (2D array)

- the combination of multiple 1-D array is called 2D array 

**Creation**

In [2]:
import numpy as np

In [19]:
l = [[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]]
a = np.array(l)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [7]:
print(a.ndim)
print(a.shape)
# a.shape = (number of previes dimention array, number of values inside the previos dimention array)
# or
# (number of rows,number of coloumn)

2
(4, 4)


In [5]:
b = np.zeros((4,3),dtype=int)
print(b)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [7]:
b= np.ones((4,3),dtype=int)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [13]:
b =np.eye(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
b = np.diag([1,5,9,16])
print(b)

[[ 1  0  0  0]
 [ 0  5  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


**Extraction**

**extracting Single value by column and row**

In [3]:
# extrat the value from first row and 2 column which is 6
a[1,2]

np.int64(6)

**extracting multiple values by slicing**

In [5]:
#extract 1 and 2nd row with all column

a[1:3,:]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**extracting by using list of rows and coloums**

In [22]:
# extract the values from row [0,1,3] and coloum [0,2,3]
print(a)
a[[0,1,3],[0,2,3]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([ 0,  6, 15])

# Modification

**Replace**

In [23]:
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [24]:
#replace 11 with 20
a[2,3] = 20
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 20]
 [12 13 14 15]]


In [27]:
#replace complet 1st row with 16,17,18,19

a[1,:]= [16,17,18,19]
print(a)

[[ 0  1  2  3]
 [16 17 18 19]
 [ 8  9 10 20]
 [12 13 14 15]]


In [28]:
# replace 0,9,15 with 1

a[[0,2,3],[0,1,3]] = 1
print(a)

[[ 1  1  2  3]
 [16 17 18 19]
 [ 8  1 10 20]
 [12 13 14  1]]


In [33]:
# replace last 3 rows with different values

a[1:4,:] = [[4,5,6,7],[8,9,10,11],[12,13,14,15]]
print(a)

[[ 1  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


**with append function**

In [39]:
b = np.append(a,[[4,8,12,16]],axis=0)
print(b)

[[ 1  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 4  8 12 16]]


# Stack

- stack is use to combine multiple 2D array of same shape

# VSTACK

- combine the 2D arrays vertically

In [51]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print(a)
print(b)

c = np.vstack((a,b))
print("vstack output")
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
vstack output
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


# HSTACK

- combine the 2D array horizontally

In [52]:
d = np.hstack((a,b))
print(d)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [53]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [59]:
b = np.hstack([a,[[4],[7],[10]]])
print(b)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


# Delete

**delete single row or column**

In [60]:
 print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
# delete row
b = np.delete(a,[1],axis=0)
print(b)

[[1 2 3]
 [7 8 9]]


In [62]:
# delete column
b = np.delete(a,[1],axis=1)
print(b)

[[1 3]
 [4 6]
 [7 9]]


**Delete multiple column and row**

In [63]:
print(d)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [64]:
b = np.delete(d,[1,2],axis=0)
print(b)

[[ 1  2  3 10 11 12]]


In [65]:
b = np.delete(d,[1,3,5],axis=1)
print(b)

[[ 1  3 11]
 [ 4  6 14]
 [ 7  9 17]]


# conversion of array from one dimention to another

**convert 2D to 1D array**

In [66]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

b = a.ravel()
print(b)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


**convert 1D to 2D**

In [68]:
a = np.array([1,2,3,4,5,6])
print(a)

b = np.reshape(a,(3,2))
print(b)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]



**convert 2D to 2D**

In [71]:
print(d)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [76]:
b = np.reshape(d,(9,2))
print(b)

[[ 1  2]
 [ 3 10]
 [11 12]
 [ 4  5]
 [ 6 13]
 [14 15]
 [ 7  8]
 [ 9 16]
 [17 18]]


**Transpose**

In [78]:
d.T

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [79]:
b = np.sort(d,axis=1)
print(b)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


# Operation

In [81]:
print(d)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [82]:
d+10

array([[11, 12, 13, 20, 21, 22],
       [14, 15, 16, 23, 24, 25],
       [17, 18, 19, 26, 27, 28]])

In [84]:
d==10

array([[False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [88]:
print(c)
c = np.reshape(c,(3,6))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [89]:
d+c

array([[ 2,  4,  6, 14, 16, 18],
       [11, 13, 15, 23, 25, 27],
       [20, 22, 24, 32, 34, 36]])