# Numpy

**Numerical python**
- used for working with arrays
- in python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy is incredible library to perform mathematicl and statistical operations due to it's fast and memory efficient as it is optimized to work with latest CPU architectures
- NumPy aims to provide an array object that is up to 50x faster than traditional python lists. so processes can access and manipulate them very efficiently 


# Dimentions

1) 0D
   - the value of fundamental data type which are int, float, bool, str are called 0D array 
2) 1D
   - the combination of multiple 0D array is called as 1D array
3) 2D
   - the combination of multiple 1D array is called as 2D array
4) 3D
   - the combination of multiple 2D array is called as 3D array

   -
   -
   -
   -


# Order / Priority 

1) object -> str
2) float
3) int
4) bool

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [5]:
a = 45
print(a)
print(type(a))

45
<class 'int'>


In [6]:
a = 45
arr_0 = np.array(a)
print(arr_0)
print(type(arr_0))

45
<class 'numpy.ndarray'>


# 1-D

In [7]:
t = 1,2,20,24,35,75,23,89
ta = np.array(t)
print(ta)

[ 1  2 20 24 35 75 23 89]


In [8]:
l = [1,2,3,4,5,6, 2.4, 5.6]
la1 = np.array(l)
print(la1)


[1.  2.  3.  4.  5.  6.  2.4 5.6]


In [9]:
l2 = [1,2,3,4,5,6, 2.4, 5.6]
la1 = np.array(l,dtype=int) #by default it will convert data type as per priority but we can define manually aswell 
print(la1)

[1 2 3 4 5 6 2 5]


In [12]:
d = {'a':22,'b':33,'c':44}
da = np.array(d)
print(type (da))

<class 'numpy.ndarray'>


# Shape and dimention of array 

In [13]:
a = 45
arr_0 = np.array(a)
arr_0.ndim       #number of dimention 0d,1d,2d.....

0

In [14]:
l = [1,2,3,4,5,6, 2.4, 5.6]
la1 = np.array(l)
la1.ndim

1

In [15]:
arr_0.shape #shows the number of values in array for 0D it gives empty tuple 

()

In [17]:
la1.shape #for 1-D it will give (len,)

(8,)

# convert array to list

In [21]:
a = la1.tolist()
print (type(a))
print(a)

<class 'list'>
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 2.4, 5.6]


# creation and modification and Aplication of 1-D array

# creation 

**There are 4 ways to create 1-D array**

1) create with own values - np.array()
2) create with sequence values - np.arange()
3) create with random values - np.random.randint()
4) create with same values - np.zeros()

In [23]:
# 1 create with own values - np.array()
l = [1,2,3,4,5,6, 2.4, 5.6]
la = np.array(l)
print(la)

[1.  2.  3.  4.  5.  6.  2.4 5.6]


In [24]:
# 2 create with sequence values - np.arange()
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [25]:
# 3 create with random values - np.random.randint()

a = np.random.randint(1,10,5)
print(a)

[1 5 3 6 3]


In [26]:
# create with same values - np.zeros()
a = np.zeros(4) # by default it will give float zero values 
print(a)

[0. 0. 0. 0.]


In [29]:
a = np.zeros((4,),dtype=int)+20
print(a)

[20 20 20 20]


In [6]:
a = np.ones((4,),dtype=int)
print(a)

[1 1 1 1]


In [15]:
a = np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


# Extraction 

- there are three ways to extract the values

1) indexing
2) slicing
3) condition  

**Indexing**

In [33]:
l = np.array(l,dtype=int)
print(l)

[1 2 3 4 5 6 2 5]


In [34]:
l[3]

np.int64(4)

In [35]:
l[-5]

np.int64(4)

**Sclicing**

In [36]:
l[1:6:2]

array([2, 4, 6])

In [41]:
l[3:6:-1]

array([], dtype=int64)

**Accessing a multiple values based on index list**

In [37]:
l[[1,2,4,6]]

array([2, 3, 5, 2])

**Accessing the values base on the condition**

In [38]:
l[l>4]

array([5, 6, 5])

In [40]:
l[(l<3) | (l>5)]

array([1, 2, 6, 2])

In [43]:
l[l%2==0]

array([2, 4, 6, 2])

# Modify the values in Numpy

**1) Replacing the value** 

In [16]:
l = [10,20,40,50,30,20,60,70,90]

a = np.array(l,dtype=int)

In [17]:
print(a)

[10 20 40 50 30 20 60 70 90]


**replacing single value**

In [18]:
# replace 50 with 20
a[3]=20
print(a)

[10 20 40 20 30 20 60 70 90]


**replacing multiple values**

In [21]:
# replace last 4 values 50
a[-4::] = 50
print(a)

[10 20 40 20 30 50 50 50 50]


In [22]:
# replace last 4 values with 10,20,30,40
a[5::] = [10,20,30,40]
print(a)

[10 20 40 20 30 10 20 30 40]


In [24]:
#replace with list of index number [1,3,4,7,8] with 10
a[[1,3,4,7,8]]=10
print(a)

[10 10 40 10 10 10 25 10 10]


**base on the condition**

In [23]:
# replace all 20 with 25
a[(a==20)] = 25
print(a)

[10 25 40 25 30 10 25 30 40]


**np.append function**

In [26]:
aa = np.append(a,[15,25,50,55,"srk"])
print(aa)

['10' '10' '40' '10' '10' '10' '25' '10' '10' '15' '25' '50' '55' 'srk']


# Delete the values from the array

**delete single value from the array**

In [27]:
print(a)

[10 10 40 10 10 10 25 10 10]


In [29]:
#delete 25 from the array
a = np.delete(a,6)
print(a)

[10 10 40 10 10 10 10 10]


**delete multiple values**

In [30]:
#delete 2,4,5,7 index value

a = np.delete(a,[2,4,5,7])
print(a)

[10 10 10 10]


In [31]:
#delete by condition equel to 10

a = np.delete(a,(a==10))
print(a)

[]


# Application

**sorting**

In [32]:
a = np.array([4,6,8,2,1])
b = np.sort(a)
print(b)

[1 2 4 6 8]


**shallow copy**

In [34]:
b=a.copy()
print(b)

[4 6 8 2 1]


# Opertaions

In [38]:
a = list(range(1,15,2))
print(a)
a = np.array(a)
print(a)

b =a+5
print(b)

[1, 3, 5, 7, 9, 11, 13]
[ 1  3  5  7  9 11 13]
[ 6  8 10 12 14 16 18]


In [39]:
c=a
print(c)

[ 1  3  5  7  9 11 13]


In [41]:
d = b+c #it only work if both array have same shape
print(d)

[ 7 11 15 19 23 27 31]


**comparison operation**

In [42]:
print(a)
print(c)

a == c

[ 1  3  5  7  9 11 13]
[ 1  3  5  7  9 11 13]


array([ True,  True,  True,  True,  True,  True,  True])

In [43]:
c > a

array([False, False, False, False, False, False, False])

In [44]:
c <=10

array([ True,  True,  True,  True,  True, False, False])

In [46]:
np.array_equal(a,b)

False

In [48]:
np.array_equal(a,c)

True

**Mathematical operation**

In [49]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [50]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [51]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [52]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])