# Numpy

**Numerical python**
- used for working with arrays
- in python we have lists that serve the purpose of arrays, but they are slow to process.
- NumPy is incredible library to perform mathematicl and statistical operations due to it's fast and memory efficient as it is optimized to work with latest CPU architectures
- NumPy aims to provide an array object that is up to 50x faster than traditional python lists. so processes can access and manipulate them very efficiently 


# Dimentions

1) 0D
   - the value of fundamental data type which are int, float, bool, str are called 0D array 
2) 1D
   - the combination of multiple 0D array is called as 1D array
3) 2D
   - the combination of multiple 1D array is called as 2D array
4) 3D
   - the combination of multiple 2D array is called as 3D array

   -
   -
   -
   -


# Order / Priority 

1) object -> str
2) float
3) int
4) bool

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
a = 45
print(a)
print(type(a))

45
<class 'int'>


In [6]:
a = 45
arr_0 = np.array(a)
print(arr_0)
print(type(arr_0))

45
<class 'numpy.ndarray'>


# 1-D

In [7]:
t = 1,2,20,24,35,75,23,89
ta = np.array(t)
print(ta)

[ 1  2 20 24 35 75 23 89]


In [8]:
l = [1,2,3,4,5,6, 2.4, 5.6]
la1 = np.array(l)
print(la1)


[1.  2.  3.  4.  5.  6.  2.4 5.6]


In [9]:
l2 = [1,2,3,4,5,6, 2.4, 5.6]
la1 = np.array(l,dtype=int) #by default it will convert data type as per priority but we can define manually aswell 
print(la1)

[1 2 3 4 5 6 2 5]


In [12]:
d = {'a':22,'b':33,'c':44}
da = np.array(d)
print(type (da))

<class 'numpy.ndarray'>


# Shape and dimention of array 

In [13]:
a = 45
arr_0 = np.array(a)
arr_0.ndim       #number of dimention 0d,1d,2d.....

0

In [14]:
l = [1,2,3,4,5,6, 2.4, 5.6]
la1 = np.array(l)
la1.ndim

1

In [15]:
arr_0.shape #shows the number of values in array for 0D it gives empty tuple 

()

In [17]:
la1.shape #for 1-D it will give (len,)

(8,)

# conver array to list

In [21]:
a = la1.tolist()
print (type(a))
print(a)

<class 'list'>
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 2.4, 5.6]


# creation and modification and Aplication of 1-D array

# creation 

**There are 4 ways to create 1-D array**

1) create with own values - np.array()
2) create with sequence values - np.arange()
3) create with random values - np.random.randint()
4) create with same values - np.zeros()

In [23]:
# 1 create with own values - np.array()
l = [1,2,3,4,5,6, 2.4, 5.6]
la = np.array(l)
print(la)

[1.  2.  3.  4.  5.  6.  2.4 5.6]


In [24]:
# 2 create with sequence values - np.arange()
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [25]:
# 3 create with random values - np.random.randint()

a = np.random.randint(1,10,5)
print(a)

[1 5 3 6 3]


In [26]:
# create with same values - np.zeros()
a = np.zeros(4) # by default it will give float zero values 
print(a)

[0. 0. 0. 0.]


In [29]:
a = np.zeros((4,),dtype=int)+20
print(a)

[20 20 20 20]


# Extraction 

**Indexing**

In [33]:
l = np.array(l,dtype=int)
print(l)

[1 2 3 4 5 6 2 5]


In [34]:
l[3]

np.int64(4)

In [35]:
l[-5]

np.int64(4)

**Sclicing**

In [36]:
l[1:6:2]

array([2, 4, 6])

In [41]:
l[3:6:-1]

array([], dtype=int64)

**Accessing a multiple values based on index list**

In [37]:
l[[1,2,4,6]]

array([2, 3, 5, 2])

**Accessing the values base on the condition**

In [38]:
l[l>4]

array([5, 6, 5])

In [40]:
l[(l<3) | (l>5)]

array([1, 2, 6, 2])

In [43]:
l[l%2==0]

array([2, 4, 6, 2])